### PR TITLE
Fix resolving non-js files

### LINKED ISSUE #5: Support for TypeScript files
### Description

Is it possible to add builtin support for `.ts`, `.mts` and `.cts` files?

I'm using this library and running tests on a TypeScript monorepo codebase. During development the "exports" field entrypoints redirect to TypeScript files via symlinks. This breaks with the following error.

```bash
ERR_UNKNOWN_FILE_EXTENSION - Unknown file extension ".ts" for X
```

I'm happy to open a PR and add the extensions, if you think it's a good idea.

https://github.com/wooorm/import-meta-resolve/blob/937d3f33413bf61d2e85e866d4650cb38ebd94cb/lib/get-format.js#L14-L22

### PR DESCRIPTION
**Pull request by ifiokjr**
Add support for resolving TypeScript files

Closes #5

### CODE REVIEW

File: lib/get-format.js [hunk 1]
```diff
@@ -18,7 +18,10 @@ const extensionFormatMap = {
   '.cjs': 'commonjs',
   '.js': 'module',
   '.json': 'json',
-  '.mjs': 'module'
+  '.mjs': 'module',
+  '.ts': 'module',
+  '.cts': 'commonjs',
+  '.mts': 'module'
```
Comment (nicolo-ribaudo) [inline lib/get-format.js:24]: I'd be _very surprised_ if node hard-codes TS-specific extensions. Doesn't it have a generic fallback for any unknown file type?

Comment (nicolo-ribaudo) [reply lib/get-format.js:24]: It looks like the fix should go in the `getFileProtocolModuleFormat`, where Node.js implements the fallback:
https://github.com/nodejs/node/blob/40fa2e9c110c616b1301c20c2a3cdb2cf6cc165e/lib/internal/modules/esm/get_format.js#L83

Comment (nicolo-ribaudo) [reply lib/get-format.js:24]: It looks like the fix should go in the getFileProtocolModuleFormat, where Node.js has an additional ignoreError parameter to suppress that error:
[nodejs/node@40fa2e9/lib/internal/modules/esm/get_format.js#L66-L67](https://github.com/nodejs/node/blob/40fa2e9c110c616b1301c20c2a3cdb2cf6cc165e/lib/internal/modules/esm/get_format.js#L66-L67)

Comment (nicolo-ribaudo) [reply lib/get-format.js:24]: And that parameter is explicitly set to `true`: https://github.com/nodejs/node/blob/40fa2e9c110c616b1301c20c2a3cdb2cf6cc165e/lib/internal/modules/esm/get_format.js#L107-L111

Comment (ifiokjr) [reply lib/get-format.js:24]: Yeah makes sense. This is the patch I applied to get things working in my local branch. I'll take a closer look.

Comment (wooorm) [reply lib/get-format.js:24]: Thanks for working on a fix! :)
The extension map is indeed *not supposed to be changed*.
Nicolò’s comment points to `getFileProtocolModuleFormat`, which in Node receives an `ignoreErrors` and `returns undefined` if that is passed.
That should be accepted.
Furthermore, it should be passed as `true` from `defaultGetFormatWithoutErrors`.

Comment (ifiokjr) [reply lib/get-format.js]: @nicolo-ribaudo I've made modifications to better reflect the way node is doing things (based on the links provided).

File: lib/get-format.js [hunk 2]
```diff
@@ -18,7 +18,9 @@ const extensionFormatMap = {
   '.cjs': 'commonjs',
   '.js': 'module',
   '.json': 'json',
-  '.mjs': 'module'
+  '.mjs': 'module',
+  // Taken from https://github.com/nodejs/node/blob/595ce9dac63cdd32d893c3319328a752719644d2/lib/internal/modules/esm/formats.js#L28-L30
+  '.wasm': 'wasm'
```
Comment (ifiokjr) [inline lib/get-format.js:23]: I've added the wasm module as a builtin format since it looks like that's the intention from as shown in the link provided.

File: lib/get-format.js [hunk 3]
```diff
@@ -60,8 +66,11 @@ function getDataProtocolModuleFormat(parsed) {
 
 /**
  * @param {URL} url
+ * @param {{parentURL: string}} _context
+ * @param {boolean} ignoreErrors
+ * @returns {string|null}
  */
-function getFileProtocolModuleFormat(url) {
+function getFileProtocolModuleFormat(url, _context, ignoreErrors) {
```
Comment (ifiokjr) [inline lib/get-format.js:73]: Added `ignoreErrors` which is set to `true` in the default `resolve` export.

File: lib/get-format.js [hunk 4]
```diff
@@ -71,6 +80,9 @@ function getFileProtocolModuleFormat(url) {
   const format = extensionFormatMap[ext]
   if (format) return format
 
+  // Taken from https://github.com/nodejs/node/blob/master/lib/internal/modules/esm/get_format.js#L66-L67
```
Comment (ifiokjr) [inline lib/get-format.js:83]: I can remove the line comments since they might be too noisy.

Comment (nicolo-ribaudo) [reply lib/get-format.js:83]: And it's already present at the beginning of the file 😉

File: lib/get-format.js (hunk 2 above)
Comment (wooorm) [inline lib/get-format.js:23]:
```suggestion
```

Please drop it for now. The `experimentalWasmModules` flag is not supported (see readme). If needed, we can add it later.

File: lib/get-format.js [hunk 5]
```diff
@@ -36,7 +38,11 @@ function mimeToFormat(mime) {
 }
 
 /**
- * @type {Record<string, (parsed: URL) => string|null>}
+ * @typedef {(parsed: URL, context: {parentURL: string}, ignoreErrors: boolean) => string|null} ProtocolHandler
```
Comment (wooorm) [inline lib/get-format.js:41]: You can use the longer form to more explicitly define functions:

```suggestion
 * @callback ProtocolHandler
 * @param {URL} parsed
 * @param {{parentURL: string}} context
 * @param {boolean} ignoreErrors
 * @returns {string|null}
```

File: lib/get-format.js [hunk 6]
```diff
@@ -60,8 +66,11 @@ function getDataProtocolModuleFormat(parsed) {
 
 /**
  * @param {URL} url
+ * @param {{parentURL: string}} _context
+ * @param {boolean} ignoreErrors
+ * @returns {string|null}
```
Comment (wooorm) [inline lib/get-format.js:71]:
```suggestion
 * @type {ProtocolHandler}
```

Now that the function is defined as a type, it can be reused here

File: lib/get-format.js (hunk 4 above)
Comment (wooorm) [inline lib/get-format.js:83]:
```suggestion
```

The comment at the top of the file should be fine!

File: lib/get-format.js (hunk 2 above)
Comment (wooorm) [reply lib/get-format.js:23]: Given that `.ts` etc can now also be loaded, without it being in the map, my guess is also it that it doesn’t have to be added and the test you added will work fine even without it?

**Review by wooorm — COMMENTED** [review]
Thanks, couple of style nits, but starting to look good!

**Review by wooorm — APPROVED** [review]
Thanks for all your work! This looks great, thanks!

**Comment by wooorm** [comment]
Thanks, [released](https://github.com/wooorm/import-meta-resolve/releases/tag/2.0.3)!
